// src/lib/zip-generator.ts
// Generates a real Next.js 15 project ZIP from analysis results

import type { AnalysisResult, DetectedFont } from '@/types'

export async function generateProjectZip(result: AnalysisResult): Promise<Buffer> {
  const JSZip = (await import('jszip')).default
  const zip = new JSZip()

  const slug = result.url
    .replace(/https?:\/\//, '')
    .split('/')[0]
    .replace(/[^a-z0-9]/gi, '-')
    .toLowerCase()

  const root = zip.folder(`${slug}-clone`)!
  const src = root.folder('src')!
  const app = src.folder('app')!
  const components = src.folder('components')!
  const lib = src.folder('lib')!
  const pub = root.folder('public')!

  const fonts = result.fonts || []
  const c = result.colors
  const t = result.typography

  // ── Root files ──────────────────────────────────────────────────────────────

  root.file('package.json', generatePackageJson(slug))
  root.file('tsconfig.json', generateTsConfig())
  root.file('next.config.ts', generateNextConfig(result.url))
  root.file('tailwind.config.ts', generateTailwindConfig(result))
  root.file('postcss.config.mjs', `const config = { plugins: { '@tailwindcss/postcss': {} } }\nexport default config`)
  root.file('.env.example', generateEnvExample(result.url))
  root.file('.gitignore', generateGitignore())
  root.file('README.md', generateReadme(slug, result))

  // ── App directory ───────────────────────────────────────────────────────────

  app.file('layout.tsx', generateLayout(slug, fonts, result))
  app.file('globals.css', generateGlobalCss(result))
  app.file('page.tsx', result.nextjsCode || generateFallbackPage(result))

  // ── Components ──────────────────────────────────────────────────────────────

  components.file('ui/button.tsx', generateButtonComponent(result))
  components.file('ui/card.tsx', generateCardComponent(result))

  // ── Lib ─────────────────────────────────────────────────────────────────────

  lib.file('utils.ts', `import { clsx, type ClassValue } from 'clsx'\nimport { twMerge } from 'tailwind-merge'\n\nexport function cn(...inputs: ClassValue[]) {\n  return twMerge(clsx(inputs))\n}`)

  // ── Public ──────────────────────────────────────────────────────────────────

  pub.file('index.html', result.htmlCode || '')

  // ── Design system files ─────────────────────────────────────────────────────

  root.file('design-tokens.json', JSON.stringify({
    generatedAt: result.analyzedAt,
    source: result.url,
    framework: result.framework,
    style: result.style,
    styleNotes: result.styleNotes,
    colors: result.colors,
    typography: result.typography,
    spacing: result.spacing,
    effects: result.effects,
    fonts: result.fonts,
    components: result.components,
  }, null, 2))

  root.file('infrastructure.json', JSON.stringify(result.infrastructure || {}, null, 2))

  root.file('security-report.md', generateSecurityReport(result))

  root.file('VIBE_PROMPT.md', `# Vibe Coding Prompt\n## Source: ${result.url}\n## Generated: ${result.analyzedAt}\n\n---\n\n${result.vibePrompt}`)

  return zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  })
}

// ── File generators ───────────────────────────────────────────────────────────

function generatePackageJson(slug: string): string {
  return JSON.stringify({
    name: `${slug}-clone`,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
      'type-check': 'tsc --noEmit',
    },
    dependencies: {
      next: '15.3.0',
      react: '^19.0.0',
      'react-dom': '^19.0.0',
      'class-variance-authority': '^0.7.0',
      clsx: '^2.1.1',
      'tailwind-merge': '^2.5.4',
    },
    devDependencies: {
      tailwindcss: '^4.0.0',
      '@tailwindcss/postcss': '^4.0.0',
      typescript: '^5.6.3',
      '@types/react': '^19.0.0',
      '@types/node': '^22.0.0',
      'eslint-config-next': '15.3.0',
    },
  }, null, 2)
}

function generateTsConfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: 'ES2017',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./src/*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  }, null, 2)
}

function generateNextConfig(sourceUrl: string): string {
  return `import type { NextConfig } from 'next'

// Generated by DesignClone AI — cloned from ${sourceUrl}
const nextConfig: NextConfig = {
  images: {
    remotePatterns: [{ protocol: 'https', hostname: '**' }],
  },
}

export default nextConfig
`
}

function generateTailwindConfig(r: AnalysisResult): string {
  const c = r.colors
  const fonts = r.fonts || []
  const fontFamilyLines = fonts.length
    ? fonts.map(f => `      ${f.tailwindKey || 'sans'}: ['"${f.family}"', '${f.category || 'sans-serif'}'],`).join('\n')
    : `      sans: ['"${r.typography.primaryFont || 'Inter'}"', 'sans-serif'],`

  return `import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        primary: '${c?.primary || '#000000'}',
        secondary: '${c?.secondary || '#333333'}',
        accent: '${c?.accent || '#666666'}',
        background: '${c?.background || '#ffffff'}',
        surface: '${c?.surface || '#f5f5f5'}',
        'text-default': '${c?.text || '#1a1a1a'}',
        'text-muted': '${c?.textMuted || '#888888'}',
        border: '${c?.border || '#e5e5e5'}',
      },
      fontFamily: {
${fontFamilyLines}
      },
      borderRadius: {
        DEFAULT: '${r.effects?.borderRadius || '8px'}',
      },
      maxWidth: {
        container: '${r.spacing?.containerMaxWidth || '1200px'}',
      },
    },
  },
} satisfies Config

export default config
`
}

function generateEnvExample(sourceUrl: string): string {
  return `# Generated by DesignClone AI — cloned from ${sourceUrl}

# Browserless for scraping (optional in cloned project)
BROWSERLESS_API_KEY=your_key_here

# Add your own services below:
# DATABASE_URL=
# NEXTAUTH_SECRET=
# NEXTAUTH_URL=http://localhost:3000
`
}

function generateGitignore(): string {
  return `.DS_Store
node_modules/
.next/
out/
.env
.env.local
.env.*.local
*.tsbuildinfo
.vercel
`
}

function generateLayout(slug: string, fonts: DetectedFont[], r: AnalysisResult): string {
  const primaryFont = fonts[0]
  const fontImportName = primaryFont?.family.replace(/\s+/g, '_') || ''
  const hasGoogleFont = primaryFont?.isGoogleFont && primaryFont.family

  return `import type { Metadata } from 'next'
${hasGoogleFont ? `import { ${fontImportName.replace(/[^a-zA-Z_]/g, '')} } from 'next/font/google'` : ''}
import './globals.css'

export const metadata: Metadata = {
  title: '${slug}',
  description: 'Cloned with DesignClone AI',
}
${hasGoogleFont ? `
const font = ${fontImportName.replace(/[^a-zA-Z_]/g, '')}({
  subsets: ['latin'],
  weight: [${(primaryFont!.weights || ['400']).map(w => `'${w}'`).join(', ')}],
  variable: '${primaryFont!.cssVariable || '--font-primary'}',
})
` : ''}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body${hasGoogleFont ? ` className={font.variable}` : ''}>{children}</body>
    </html>
  )
}
`
}

function generateGlobalCss(r: AnalysisResult): string {
  const fonts = r.fonts || []
  const imports = fonts
    .filter(f => f.isGoogleFont && f.importUrl)
    .map(f => `@import url('${f.importUrl}');`)
    .join('\n')

  return `${imports}

@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --color-primary: ${r.colors?.primary || '#000000'};
  --color-secondary: ${r.colors?.secondary || '#333333'};
  --color-accent: ${r.colors?.accent || '#666666'};
  --color-background: ${r.colors?.background || '#ffffff'};
  --color-surface: ${r.colors?.surface || '#f5f5f5'};
  --color-text: ${r.colors?.text || '#1a1a1a'};
  --color-text-muted: ${r.colors?.textMuted || '#888888'};
  --color-border: ${r.colors?.border || '#e5e5e5'};
  --radius: ${r.effects?.borderRadius || '8px'};
}

* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  background: var(--color-background);
  color: var(--color-text);
  font-size: ${r.typography?.bodySize || '15px'};
  line-height: ${r.typography?.lineHeight || '1.6'};
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

h1, h2, h3, h4, h5, h6 {
  letter-spacing: ${r.typography?.letterSpacing || 'normal'};
  font-weight: ${r.typography?.fontWeight?.split('/').pop() || '600'};
}
`
}

function generateButtonComponent(r: AnalysisResult): string {
  return `import { cn } from '@/lib/utils'

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'ghost'
  size?: 'sm' | 'md' | 'lg'
}

export function Button({
  variant = 'primary',
  size = 'md',
  className,
  children,
  ...props
}: ButtonProps) {
  return (
    <button
      className={cn(
        'inline-flex items-center justify-center font-medium transition-all',
        'rounded-[var(--radius)] cursor-pointer',
        {
          primary: 'bg-primary text-white hover:opacity-90',
          secondary: 'bg-surface text-default border border-border hover:bg-background',
          ghost: 'text-muted hover:text-default',
        }[variant],
        {
          sm: 'text-xs px-3 py-1.5',
          md: 'text-sm px-4 py-2',
          lg: 'text-base px-6 py-3',
        }[size],
        className
      )}
      {...props}
    >
      {children}
    </button>
  )
}
`
}

function generateCardComponent(r: AnalysisResult): string {
  return `import { cn } from '@/lib/utils'

interface CardProps {
  className?: string
  children: React.ReactNode
}

export function Card({ className, children }: CardProps) {
  return (
    <div
      className={cn(
        'bg-surface border border-border rounded-[var(--radius)]',
        '${r.effects?.boxShadow === 'subtle' ? 'shadow-sm' : r.effects?.boxShadow === 'medium' ? 'shadow-md' : ''}',
        className
      )}
    >
      {children}
    </div>
  )
}

export function CardHeader({ className, children }: CardProps) {
  return <div className={cn('p-6 border-b border-border', className)}>{children}</div>
}

export function CardContent({ className, children }: CardProps) {
  return <div className={cn('p-6', className)}>{children}</div>
}
`
}

function generateFallbackPage(r: AnalysisResult): string {
  return `export default function Page() {
  return (
    <main className="min-h-screen bg-background">
      <nav className="border-b border-border px-6 py-4">
        <div className="max-w-container mx-auto">
          <span className="font-semibold text-default">Brand</span>
        </div>
      </nav>
      <section className="max-w-container mx-auto px-6 py-24 text-center">
        <h1 className="text-5xl font-bold text-default mb-6">
          Welcome
        </h1>
        <p className="text-text-muted text-lg max-w-xl mx-auto">
          Generated by DesignClone AI from ${r.url}
        </p>
      </section>
    </main>
  )
}
`
}

function generateSecurityReport(r: AnalysisResult): string {
  const sec = r.security
  if (!sec) return '# Security Report\n\nNo security data available.'

  const vulns = sec.vulnerabilities || []
  const critical = vulns.filter(v => v.severity === 'critical')
  const high = vulns.filter(v => v.severity === 'high')
  const medium = vulns.filter(v => v.severity === 'medium')
  const low = vulns.filter(v => v.severity === 'low' || v.severity === 'info')

  return `# Security Report — ${r.url}
Generated: ${r.analyzedAt}
Tool: DesignClone AI

## Executive Summary

| Metric | Value |
|--------|-------|
| Overall Score | ${sec.overallScore}/100 (${sec.scoreLabel}) |
| Risk Level | ${sec.riskLevel} |
| Total Vulnerabilities | ${vulns.length} |
| Critical | ${critical.length} |
| High | ${high.length} |
| Medium | ${medium.length} |
| Low / Info | ${low.length} |

## SSL / TLS Configuration

| Property | Value |
|----------|-------|
| Grade | ${sec.ssl?.grade || '—'} |
| TLS Version | ${sec.ssl?.tlsVersion || '—'} |
| HSTS | ${sec.ssl?.hsts ? '✓ Enabled' : '✗ Missing'} |
| HSTS max-age | ${sec.ssl?.hstsMaxAge || '—'} |
| Certificate Provider | ${sec.ssl?.provider || '—'} |

## HTTP Security Headers

| Header | Status |
|--------|--------|
| Content-Security-Policy | ${sec.headers?.contentSecurityPolicy || '—'} |
| Strict-Transport-Security | ${sec.headers?.strictTransportSecurity || '—'} |
| X-Frame-Options | ${sec.headers?.xFrameOptions || '—'} |
| X-Content-Type-Options | ${sec.headers?.xContentTypeOptions || '—'} |
| Referrer-Policy | ${sec.headers?.referrerPolicy || '—'} |
| Permissions-Policy | ${sec.headers?.permissionsPolicy || '—'} |
| Cross-Origin-Opener-Policy | ${sec.headers?.crossOriginOpenerPolicy || '—'} |
| Cross-Origin-Resource-Policy | ${sec.headers?.crossOriginResourcePolicy || '—'} |

## Protection Mechanisms

- **Rate Limiting:** ${sec.rateLimit}
- **Bot Protection:** ${sec.botProtection}
- **DDoS Protection:** ${sec.ddosProtection}

## Vulnerabilities

${vulns.map(v => `### [${v.severity.toUpperCase()}] ${v.id} — ${v.title}

| Field | Value |
|-------|-------|
| Category | ${v.category} |
| CVSS Score | ${v.cvss} |
| CWE | ${v.cwe} |
| Affected | ${v.affected} |

**Description:**  
${v.description}

**Evidence:**  
${v.evidence || '—'}

**Recommended Fix:**  
${v.solution}

**References:** ${(v.references || []).join(', ') || '—'}

---`).join('\n\n')}

## Priority Recommendations

${(sec.recommendations || []).map((r, i) => `${i + 1}. ${r}`).join('\n')}
`
}

function generateReadme(slug: string, r: AnalysisResult): string {
  return `# ${slug}-clone

Cloned from **[${r.url}](${r.url})** using **DesignClone AI**.

## Stack
- **Next.js 15** (App Router, React 19)
- **Tailwind CSS 4**
- **TypeScript**

## Detected design system
- **Framework:** ${r.framework} (${Math.round(r.frameworkConfidence * 100)}% confidence)
- **Style:** ${r.style}
- **Primary color:** ${r.colors?.primary}
- **Typography:** ${r.typography?.primaryFont}

## Fonts
${(r.fonts || []).map(f => `- **${f.family}** (${f.role}) — [Google Fonts](${f.importUrl})`).join('\n') || '- ' + r.typography?.primaryFont}

## Getting started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000).

## Files

| File | Description |
|------|-------------|
| \`src/app/page.tsx\` | Main homepage (cloned) |
| \`src/app/globals.css\` | Global styles + font imports |
| \`src/components/ui/\` | Base UI components |
| \`design-tokens.json\` | Full extracted design system |
| \`security-report.md\` | Vulnerability assessment |
| \`VIBE_PROMPT.md\` | Vibe coding prompt |

---
*Generated by DesignClone AI · ${new Date(r.analyzedAt).toLocaleDateString()}*
`
}
